### ISSUE TITLE
how open the BT file?

### ISSUE THREAD

**Issue by taurusbo** [persepolisdm/persepolis#336] opened 2017-11-22 16:15 UTC
how open the BT file?

**Comment by alireza-amirsamimi** [comment] 2017-11-23 03:07
Hello
Persepolis does not support torrent now. We hope to add it in future.

**Comment by JafarAkhondali** [comment] 2019-05-25 12:37
duplicate of https://github.com/persepolisdm/persepolis/issues/336.

**Closed as completed by JafarAkhondali** 2019-05-25 12:37 UTC
Labels: duplicate, question
