### ISSUE TITLE
How to download *torrent file use this tool on Win10 64bit OS ? thx!

### ISSUE THREAD

**Issue by ugvf2009** [persepolisdm/persepolis#223] opened 2017-06-08 01:16 UTC

**Comment by alireza-amirsamimi** [comment] 2017-06-08 06:53
@ugvf2009 Hello
Persepolis can not download torrent now. But we are planning to add it in future :)

**Comment by ugvf2009** [comment] 2017-06-09 06:48
@alireza-amirsamimi ok,thx for your reply

**Comment by jo90j00** [comment] 2017-08-10 16:21
@alireza-amirsamimi 希望能夠實現下載 .torrent BT種子檔案的文件。

**Comment by lauriehjb** [comment] 2017-11-15 03:18
@alireza-amirsamimi Hope to support torrent

**Comment by JafarAkhondali** [comment] 2019-05-25 13:03
duplicate of https://github.com/persepolisdm/persepolis/issues/501

**Closed as completed by JafarAkhondali** 2019-05-25 13:03 UTC
Labels: question
